#!/bin/sh

set -xv

repo=$(realpath hostdir/binpkgs/rrvl)

rm -f $repo/*.sig

rm -f $repo/aarch64-repodata

XBPS_ARCH=aarch64 xbps-rindex --privkey ~/.ssh/rrvl.pem --sign-pkg $repo/*.aarch64.xbps
XBPS_ARCH=aarch64 xbps-rindex -a $repo/*aarch64.xbps
XBPS_ARCH=aarch64 xbps-rindex --signedby "RRVL" --privkey ~/.ssh/rrvl.pem --sign $repo

#XBPS_ARCH=$arch xbps-rindex -c $repo
#XBPS_ARCH=$arch xbps-rindex -r $repo

echo -e "\n* Rsync'ing\n"

rsync --delete -av $* $repo/ eple.us:www/rrvl/.
#rsync -av hostdir/binpkgs/rrvl rrvl:
