#!/bin/bash

case $1 in
   pre)
        # workaround until dwc2 is fixed
        alsactl store -f /var/local/asound.state
        modprobe -r dwc2
        if [ $(grep v11 /sys/devices/platform/odroidgo2-joypad/input/input2/name) ]; then
            modprobe -r esp8089
        fi
        ;;
   post)
        alsactl restore -f /var/local/asound.state
        modprobe -r dwc2
        if [ $(grep v11 /sys/devices/platform/odroidgo2-joypad/input/input2/name) ]; then
            modprobe -r esp8089
        fi
        modprobe -i dwc2
        if [ $(grep v11 /sys/devices/platform/odroidgo2-joypad/input/input2/name) ]; then
            modprobe -i esp8089
        fi
        ;;
esac
